/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CoffeeBrandService } from "../coffeeBrand.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CoffeeBrandCreateInput } from "./CoffeeBrandCreateInput";
import { CoffeeBrandWhereInput } from "./CoffeeBrandWhereInput";
import { CoffeeBrandWhereUniqueInput } from "./CoffeeBrandWhereUniqueInput";
import { CoffeeBrandFindManyArgs } from "./CoffeeBrandFindManyArgs";
import { CoffeeBrandUpdateInput } from "./CoffeeBrandUpdateInput";
import { CoffeeBrand } from "./CoffeeBrand";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CoffeeBrandControllerBase {
  constructor(
    protected readonly service: CoffeeBrandService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CoffeeBrand",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CoffeeBrand })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: CoffeeBrandCreateInput
  ): Promise<CoffeeBrand> {
    return await this.service.create({
      data: {
        ...data,

        blend: data.blend
          ? {
              connect: data.blend,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        blend: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        label: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CoffeeBrand",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [CoffeeBrand] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(CoffeeBrandFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<CoffeeBrand[]> {
    const args = plainToClass(CoffeeBrandFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        blend: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        label: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CoffeeBrand",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CoffeeBrand })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: CoffeeBrandWhereUniqueInput
  ): Promise<CoffeeBrand | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        blend: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        label: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CoffeeBrand",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CoffeeBrand })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: CoffeeBrandWhereUniqueInput,
    @common.Body() data: CoffeeBrandUpdateInput
  ): Promise<CoffeeBrand | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          blend: data.blend
            ? {
                connect: data.blend,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          blend: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          label: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "CoffeeBrand",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CoffeeBrand })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: CoffeeBrandWhereUniqueInput
  ): Promise<CoffeeBrand | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          blend: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          label: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
