/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BlendService } from "../blend.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BlendCreateInput } from "./BlendCreateInput";
import { BlendWhereInput } from "./BlendWhereInput";
import { BlendWhereUniqueInput } from "./BlendWhereUniqueInput";
import { BlendFindManyArgs } from "./BlendFindManyArgs";
import { BlendUpdateInput } from "./BlendUpdateInput";
import { Blend } from "./Blend";
import { CoffeeBrandFindManyArgs } from "../../coffeeBrand/base/CoffeeBrandFindManyArgs";
import { CoffeeBrand } from "../../coffeeBrand/base/CoffeeBrand";
import { CoffeeBrandWhereUniqueInput } from "../../coffeeBrand/base/CoffeeBrandWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BlendControllerBase {
  constructor(
    protected readonly service: BlendService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Blend",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Blend })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: BlendCreateInput): Promise<Blend> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        origin: true,
        roast: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Blend",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Blend] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(BlendFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Blend[]> {
    const args = plainToClass(BlendFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        origin: true,
        roast: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Blend",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Blend })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: BlendWhereUniqueInput
  ): Promise<Blend | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        origin: true,
        roast: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Blend",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Blend })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: BlendWhereUniqueInput,
    @common.Body() data: BlendUpdateInput
  ): Promise<Blend | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          origin: true,
          roast: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Blend",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Blend })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: BlendWhereUniqueInput
  ): Promise<Blend | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          origin: true,
          roast: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CoffeeBrand",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/coffeeBrands")
  @ApiNestedQuery(CoffeeBrandFindManyArgs)
  async findManyCoffeeBrands(
    @common.Req() request: Request,
    @common.Param() params: BlendWhereUniqueInput
  ): Promise<CoffeeBrand[]> {
    const query = plainToClass(CoffeeBrandFindManyArgs, request.query);
    const results = await this.service.findCoffeeBrands(params.id, {
      ...query,
      select: {
        blend: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        label: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Blend",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/coffeeBrands")
  async connectCoffeeBrands(
    @common.Param() params: BlendWhereUniqueInput,
    @common.Body() body: CoffeeBrandWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      coffeeBrands: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Blend",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/coffeeBrands")
  async updateCoffeeBrands(
    @common.Param() params: BlendWhereUniqueInput,
    @common.Body() body: CoffeeBrandWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      coffeeBrands: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Blend",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/coffeeBrands")
  async disconnectCoffeeBrands(
    @common.Param() params: BlendWhereUniqueInput,
    @common.Body() body: CoffeeBrandWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      coffeeBrands: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
